version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'Homes'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root@localhost'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'platf0rm2020'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'platf0rm2020'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3307'
    expose:
      # Opens port 3307 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: